CREATE TABLE garden(_id INTEGER PRIMARY KEY AUTOINCREMENT, bedID INTEGER NOT NULL, noteID INTEGER NOT NULL);

CREATE TABLE bed(_id INTEGER PRIMARY KEY AUTOINCREMENT, noteID INTEGER NOT NULL, imageID INTEGER, layoutID INTEGER, historyID INTEGER);

CREATE TABLE image(_id INTEGER PRIMARY KEY AUTOINCREMENT, image BLOB);

CREATE TABLE layout(_id INTEGER PRIMARY KEY AUTOINCREMENT, image BLOB);

CREATE TABLE note(_id INTEGER PRIMARY KEY AUTOINCREMENT, subject STRING NOT NULL, note STRING NOT NULL);

CREATE TABLE history(_id INTEGER PRIMARY KEY AUTOINCREMENT, plantHistoryID INTEGER, workHistoryID INTEGER, harvestHistoryID INTEGER);

CREATE TABLE plant_history(_id INTEGER PRIMARY KEY AUTOINCREMENT, date DATE NOT NULL, note STRING NOT NULL);

CREATE TABLE work_history(_id INTEGER PRIMARY KEY AUTOINCREMENT, date DATE NOT NULL, note STRING NOT NULL);

CREATE TABLE harvest_history(_id INTEGER PRIMARY KEY AUTOINCREMENT, date DATE NOT NULL, note STRING NOT NULL);